"""Seed data for LabCare: common blood tests with parameters and reference ranges."""

SEED_TESTS = [
    # Hematology
    {"code": "CBC", "name": "Complete Blood Count (CBC)", "category": "Hematology", "specimen": "EDTA Whole Blood", "price": 600, "tat_hours": 4,
     "parameters": [
         {"name": "Hemoglobin", "unit": "g/dL", "ref_male": "13.5-17.5", "ref_female": "12.0-15.5", "low": 12.0, "high": 17.5},
         {"name": "Total WBC Count", "unit": "x10^3/µL", "ref_male": "4.0-11.0", "ref_female": "4.0-11.0", "low": 4.0, "high": 11.0},
         {"name": "RBC Count", "unit": "x10^6/µL", "ref_male": "4.5-5.9", "ref_female": "4.0-5.2", "low": 4.0, "high": 5.9},
         {"name": "Platelet Count", "unit": "x10^3/µL", "ref_male": "150-450", "ref_female": "150-450", "low": 150, "high": 450},
         {"name": "Hematocrit (PCV)", "unit": "%", "ref_male": "41-53", "ref_female": "36-46", "low": 36, "high": 53},
         {"name": "MCV", "unit": "fL", "ref_male": "80-100", "ref_female": "80-100", "low": 80, "high": 100},
         {"name": "MCH", "unit": "pg", "ref_male": "27-33", "ref_female": "27-33", "low": 27, "high": 33},
         {"name": "MCHC", "unit": "g/dL", "ref_male": "32-36", "ref_female": "32-36", "low": 32, "high": 36},
         {"name": "Neutrophils", "unit": "%", "ref_male": "40-70", "ref_female": "40-70", "low": 40, "high": 70},
         {"name": "Lymphocytes", "unit": "%", "ref_male": "20-45", "ref_female": "20-45", "low": 20, "high": 45},
     ]},
    {"code": "ESR", "name": "Erythrocyte Sedimentation Rate (ESR)", "category": "Hematology", "specimen": "EDTA Blood", "price": 150, "tat_hours": 2,
     "parameters": [{"name": "ESR", "unit": "mm/hr", "ref_male": "0-15", "ref_female": "0-20", "low": 0, "high": 20}]},
    {"code": "HB", "name": "Hemoglobin (HB)", "category": "Hematology", "specimen": "EDTA Blood", "price": 150, "tat_hours": 2,
     "parameters": [{"name": "Hemoglobin", "unit": "g/dL", "ref_male": "13.5-17.5", "ref_female": "12.0-15.5", "low": 12.0, "high": 17.5}]},
    {"code": "PLT", "name": "Platelet Count", "category": "Hematology", "specimen": "EDTA Blood", "price": 150, "tat_hours": 2,
     "parameters": [{"name": "Platelets", "unit": "x10^3/µL", "ref_male": "150-450", "ref_female": "150-450", "low": 150, "high": 450}]},
    {"code": "BG", "name": "Blood Group & Rh Factor", "category": "Hematology", "specimen": "EDTA Blood", "price": 200, "tat_hours": 2,
     "parameters": [{"name": "ABO Group", "unit": "", "ref_male": "A/B/AB/O", "ref_female": "A/B/AB/O", "low": None, "high": None},
                    {"name": "Rh Factor", "unit": "", "ref_male": "+/-", "ref_female": "+/-", "low": None, "high": None}]},
    {"code": "PT", "name": "Prothrombin Time (PT/INR)", "category": "Hematology", "specimen": "Citrate Blood", "price": 400, "tat_hours": 4,
     "parameters": [{"name": "PT", "unit": "sec", "ref_male": "11-13.5", "ref_female": "11-13.5", "low": 11, "high": 13.5},
                    {"name": "INR", "unit": "", "ref_male": "0.8-1.2", "ref_female": "0.8-1.2", "low": 0.8, "high": 1.2}]},
    {"code": "RETIC", "name": "Reticulocyte Count", "category": "Hematology", "specimen": "EDTA Blood", "price": 300, "tat_hours": 4,
     "parameters": [{"name": "Reticulocytes", "unit": "%", "ref_male": "0.5-2.5", "ref_female": "0.5-2.5", "low": 0.5, "high": 2.5}]},

    # Biochemistry - Diabetes
    {"code": "FBS", "name": "Fasting Blood Sugar", "category": "Biochemistry", "specimen": "Fluoride Plasma", "price": 150, "tat_hours": 2,
     "parameters": [{"name": "Glucose Fasting", "unit": "mg/dL", "ref_male": "70-100", "ref_female": "70-100", "low": 70, "high": 100}]},
    {"code": "RBS", "name": "Random Blood Sugar", "category": "Biochemistry", "specimen": "Fluoride Plasma", "price": 150, "tat_hours": 2,
     "parameters": [{"name": "Glucose Random", "unit": "mg/dL", "ref_male": "70-140", "ref_female": "70-140", "low": 70, "high": 140}]},
    {"code": "HBA1C", "name": "HbA1c (Glycated Hemoglobin)", "category": "Biochemistry", "specimen": "EDTA Blood", "price": 1200, "tat_hours": 6,
     "parameters": [{"name": "HbA1c", "unit": "%", "ref_male": "4.0-5.6", "ref_female": "4.0-5.6", "low": 4.0, "high": 5.6}]},

    # Biochemistry - Liver
    {"code": "LFT", "name": "Liver Function Tests (LFT)", "category": "Biochemistry", "specimen": "Serum", "price": 1000, "tat_hours": 6,
     "parameters": [
         {"name": "Total Bilirubin", "unit": "mg/dL", "ref_male": "0.2-1.2", "ref_female": "0.2-1.2", "low": 0.2, "high": 1.2},
         {"name": "Direct Bilirubin", "unit": "mg/dL", "ref_male": "0.0-0.3", "ref_female": "0.0-0.3", "low": 0.0, "high": 0.3},
         {"name": "SGPT (ALT)", "unit": "U/L", "ref_male": "7-56", "ref_female": "7-56", "low": 7, "high": 56},
         {"name": "SGOT (AST)", "unit": "U/L", "ref_male": "10-40", "ref_female": "10-40", "low": 10, "high": 40},
         {"name": "Alkaline Phosphatase", "unit": "U/L", "ref_male": "44-147", "ref_female": "44-147", "low": 44, "high": 147},
         {"name": "Total Protein", "unit": "g/dL", "ref_male": "6.0-8.3", "ref_female": "6.0-8.3", "low": 6.0, "high": 8.3},
         {"name": "Albumin", "unit": "g/dL", "ref_male": "3.5-5.0", "ref_female": "3.5-5.0", "low": 3.5, "high": 5.0},
     ]},
    {"code": "SGPT", "name": "SGPT (ALT)", "category": "Biochemistry", "specimen": "Serum", "price": 200, "tat_hours": 4,
     "parameters": [{"name": "SGPT (ALT)", "unit": "U/L", "ref_male": "7-56", "ref_female": "7-56", "low": 7, "high": 56}]},
    {"code": "SGOT", "name": "SGOT (AST)", "category": "Biochemistry", "specimen": "Serum", "price": 200, "tat_hours": 4,
     "parameters": [{"name": "SGOT (AST)", "unit": "U/L", "ref_male": "10-40", "ref_female": "10-40", "low": 10, "high": 40}]},
    {"code": "BIL", "name": "Bilirubin Total", "category": "Biochemistry", "specimen": "Serum", "price": 200, "tat_hours": 4,
     "parameters": [{"name": "Total Bilirubin", "unit": "mg/dL", "ref_male": "0.2-1.2", "ref_female": "0.2-1.2", "low": 0.2, "high": 1.2}]},

    # Biochemistry - Renal
    {"code": "RFT", "name": "Renal Function Tests (RFT)", "category": "Biochemistry", "specimen": "Serum", "price": 600, "tat_hours": 6,
     "parameters": [
         {"name": "Blood Urea", "unit": "mg/dL", "ref_male": "15-45", "ref_female": "15-45", "low": 15, "high": 45},
         {"name": "Creatinine", "unit": "mg/dL", "ref_male": "0.7-1.3", "ref_female": "0.6-1.1", "low": 0.6, "high": 1.3},
         {"name": "Uric Acid", "unit": "mg/dL", "ref_male": "3.4-7.0", "ref_female": "2.4-6.0", "low": 2.4, "high": 7.0},
         {"name": "Sodium (Na)", "unit": "mmol/L", "ref_male": "135-145", "ref_female": "135-145", "low": 135, "high": 145},
         {"name": "Potassium (K)", "unit": "mmol/L", "ref_male": "3.5-5.1", "ref_female": "3.5-5.1", "low": 3.5, "high": 5.1},
         {"name": "Chloride (Cl)", "unit": "mmol/L", "ref_male": "98-107", "ref_female": "98-107", "low": 98, "high": 107},
     ]},
    {"code": "UREA", "name": "Urea", "category": "Biochemistry", "specimen": "Serum", "price": 250, "tat_hours": 4,
     "parameters": [{"name": "Blood Urea", "unit": "mg/dL", "ref_male": "15-45", "ref_female": "15-45", "low": 15, "high": 45}]},
    {"code": "CREAT", "name": "Creatinine", "category": "Biochemistry", "specimen": "Serum", "price": 250, "tat_hours": 4,
     "parameters": [{"name": "Creatinine", "unit": "mg/dL", "ref_male": "0.7-1.3", "ref_female": "0.6-1.1", "low": 0.6, "high": 1.3}]},
    {"code": "UA", "name": "Uric Acid", "category": "Biochemistry", "specimen": "Serum", "price": 250, "tat_hours": 4,
     "parameters": [{"name": "Uric Acid", "unit": "mg/dL", "ref_male": "3.4-7.0", "ref_female": "2.4-6.0", "low": 2.4, "high": 7.0}]},
    {"code": "ELEC", "name": "Serum Electrolytes (Na, K, Cl)", "category": "Biochemistry", "specimen": "Serum", "price": 850, "tat_hours": 4,
     "parameters": [
         {"name": "Sodium (Na)", "unit": "mmol/L", "ref_male": "135-145", "ref_female": "135-145", "low": 135, "high": 145},
         {"name": "Potassium (K)", "unit": "mmol/L", "ref_male": "3.5-5.1", "ref_female": "3.5-5.1", "low": 3.5, "high": 5.1},
         {"name": "Chloride (Cl)", "unit": "mmol/L", "ref_male": "98-107", "ref_female": "98-107", "low": 98, "high": 107},
     ]},

    # Biochemistry - Lipid
    {"code": "LIPID", "name": "Lipid Profile", "category": "Biochemistry", "specimen": "Serum", "price": 700, "tat_hours": 6,
     "parameters": [
         {"name": "Total Cholesterol", "unit": "mg/dL", "ref_male": "<200", "ref_female": "<200", "low": 0, "high": 200},
         {"name": "Triglycerides", "unit": "mg/dL", "ref_male": "<150", "ref_female": "<150", "low": 0, "high": 150},
         {"name": "HDL Cholesterol", "unit": "mg/dL", "ref_male": ">40", "ref_female": ">50", "low": 40, "high": 999},
         {"name": "LDL Cholesterol", "unit": "mg/dL", "ref_male": "<100", "ref_female": "<100", "low": 0, "high": 100},
         {"name": "VLDL", "unit": "mg/dL", "ref_male": "5-40", "ref_female": "5-40", "low": 5, "high": 40},
     ]},

    # Biochemistry - Other
    {"code": "CA", "name": "Calcium", "category": "Biochemistry", "specimen": "Serum", "price": 300, "tat_hours": 4,
     "parameters": [{"name": "Calcium", "unit": "mg/dL", "ref_male": "8.6-10.3", "ref_female": "8.6-10.3", "low": 8.6, "high": 10.3}]},
    {"code": "PHOS", "name": "Phosphorus", "category": "Biochemistry", "specimen": "Serum", "price": 250, "tat_hours": 4,
     "parameters": [{"name": "Phosphorus", "unit": "mg/dL", "ref_male": "2.5-4.5", "ref_female": "2.5-4.5", "low": 2.5, "high": 4.5}]},
    {"code": "MG", "name": "Magnesium", "category": "Biochemistry", "specimen": "Serum", "price": 350, "tat_hours": 4,
     "parameters": [{"name": "Magnesium", "unit": "mg/dL", "ref_male": "1.7-2.2", "ref_female": "1.7-2.2", "low": 1.7, "high": 2.2}]},
    {"code": "VITD", "name": "Vitamin D3 (25-OH)", "category": "Biochemistry", "specimen": "Serum", "price": 2200, "tat_hours": 24,
     "parameters": [{"name": "25-OH Vitamin D3", "unit": "ng/mL", "ref_male": "30-100", "ref_female": "30-100", "low": 30, "high": 100}]},
    {"code": "B12", "name": "Vitamin B-12", "category": "Biochemistry", "specimen": "Serum", "price": 2000, "tat_hours": 24,
     "parameters": [{"name": "Vitamin B-12", "unit": "pg/mL", "ref_male": "200-900", "ref_female": "200-900", "low": 200, "high": 900}]},
    {"code": "FER", "name": "Ferritin", "category": "Biochemistry", "specimen": "Serum", "price": 1200, "tat_hours": 24,
     "parameters": [{"name": "Ferritin", "unit": "ng/mL", "ref_male": "20-250", "ref_female": "10-120", "low": 10, "high": 250}]},
    {"code": "IRON", "name": "Serum Iron", "category": "Biochemistry", "specimen": "Serum", "price": 500, "tat_hours": 6,
     "parameters": [{"name": "Iron", "unit": "µg/dL", "ref_male": "65-175", "ref_female": "50-170", "low": 50, "high": 175}]},
    {"code": "AMY", "name": "Amylase", "category": "Biochemistry", "specimen": "Serum", "price": 500, "tat_hours": 6,
     "parameters": [{"name": "Amylase", "unit": "U/L", "ref_male": "28-100", "ref_female": "28-100", "low": 28, "high": 100}]},
    {"code": "LIP", "name": "Lipase", "category": "Biochemistry", "specimen": "Serum", "price": 500, "tat_hours": 6,
     "parameters": [{"name": "Lipase", "unit": "U/L", "ref_male": "0-160", "ref_female": "0-160", "low": 0, "high": 160}]},
    {"code": "CKMB", "name": "CK-MB", "category": "Cardiac", "specimen": "Serum", "price": 450, "tat_hours": 6,
     "parameters": [{"name": "CK-MB", "unit": "U/L", "ref_male": "0-25", "ref_female": "0-25", "low": 0, "high": 25}]},
    {"code": "TROP", "name": "Troponin-I", "category": "Cardiac", "specimen": "Serum", "price": 2200, "tat_hours": 2,
     "parameters": [{"name": "Troponin-I", "unit": "ng/mL", "ref_male": "<0.04", "ref_female": "<0.04", "low": 0, "high": 0.04}]},

    # Endocrinology - Thyroid
    {"code": "TFT", "name": "Thyroid Function Tests (T3, T4, TSH)", "category": "Endocrinology", "specimen": "Serum", "price": 2400, "tat_hours": 24,
     "parameters": [
         {"name": "T3 (Triiodothyronine)", "unit": "ng/mL", "ref_male": "0.8-2.0", "ref_female": "0.8-2.0", "low": 0.8, "high": 2.0},
         {"name": "T4 (Thyroxine)", "unit": "µg/dL", "ref_male": "5.1-14.1", "ref_female": "5.1-14.1", "low": 5.1, "high": 14.1},
         {"name": "TSH", "unit": "µIU/mL", "ref_male": "0.4-4.0", "ref_female": "0.4-4.0", "low": 0.4, "high": 4.0},
     ]},
    {"code": "TSH", "name": "TSH (Thyroid Stimulating Hormone)", "category": "Endocrinology", "specimen": "Serum", "price": 800, "tat_hours": 24,
     "parameters": [{"name": "TSH", "unit": "µIU/mL", "ref_male": "0.4-4.0", "ref_female": "0.4-4.0", "low": 0.4, "high": 4.0}]},
    {"code": "FT3", "name": "Free T3", "category": "Endocrinology", "specimen": "Serum", "price": 800, "tat_hours": 24,
     "parameters": [{"name": "Free T3", "unit": "pg/mL", "ref_male": "2.3-4.2", "ref_female": "2.3-4.2", "low": 2.3, "high": 4.2}]},
    {"code": "FT4", "name": "Free T4", "category": "Endocrinology", "specimen": "Serum", "price": 800, "tat_hours": 24,
     "parameters": [{"name": "Free T4", "unit": "ng/dL", "ref_male": "0.8-1.8", "ref_female": "0.8-1.8", "low": 0.8, "high": 1.8}]},
    {"code": "BHCG", "name": "Beta HCG (Pregnancy)", "category": "Endocrinology", "specimen": "Serum", "price": 1200, "tat_hours": 6,
     "parameters": [{"name": "Beta HCG", "unit": "mIU/mL", "ref_male": "<5", "ref_female": "<5 (non-pregnant)", "low": 0, "high": 5}]},
    {"code": "PROL", "name": "Prolactin", "category": "Endocrinology", "specimen": "Serum", "price": 1200, "tat_hours": 24,
     "parameters": [{"name": "Prolactin", "unit": "ng/mL", "ref_male": "4-15", "ref_female": "4-23", "low": 4, "high": 23}]},
    {"code": "TEST", "name": "Testosterone", "category": "Endocrinology", "specimen": "Serum", "price": 1200, "tat_hours": 24,
     "parameters": [{"name": "Testosterone", "unit": "ng/dL", "ref_male": "280-1100", "ref_female": "15-70", "low": 15, "high": 1100}]},
    {"code": "LH", "name": "LH (Luteinizing Hormone)", "category": "Endocrinology", "specimen": "Serum", "price": 1000, "tat_hours": 24,
     "parameters": [{"name": "LH", "unit": "mIU/mL", "ref_male": "1.5-9.3", "ref_female": "1.9-12.5", "low": 1.5, "high": 12.5}]},
    {"code": "FSH", "name": "FSH (Follicle Stimulating Hormone)", "category": "Endocrinology", "specimen": "Serum", "price": 1000, "tat_hours": 24,
     "parameters": [{"name": "FSH", "unit": "mIU/mL", "ref_male": "1.5-12.4", "ref_female": "3.5-12.5", "low": 1.5, "high": 12.5}]},

    # Immunology / Serology
    {"code": "CRP", "name": "CRP (C-Reactive Protein)", "category": "Immunology", "specimen": "Serum", "price": 500, "tat_hours": 4,
     "parameters": [{"name": "CRP", "unit": "mg/L", "ref_male": "0-6", "ref_female": "0-6", "low": 0, "high": 6}]},
    {"code": "RA", "name": "RA Factor", "category": "Immunology", "specimen": "Serum", "price": 450, "tat_hours": 4,
     "parameters": [{"name": "RA Factor", "unit": "IU/mL", "ref_male": "<14", "ref_female": "<14", "low": 0, "high": 14}]},
    {"code": "ASO", "name": "ASO Titer", "category": "Immunology", "specimen": "Serum", "price": 400, "tat_hours": 4,
     "parameters": [{"name": "ASO", "unit": "IU/mL", "ref_male": "<200", "ref_female": "<200", "low": 0, "high": 200}]},
    {"code": "WIDAL", "name": "Widal Test", "category": "Serology", "specimen": "Serum", "price": 500, "tat_hours": 4,
     "parameters": [
         {"name": "S. Typhi O", "unit": "titer", "ref_male": "<1:80", "ref_female": "<1:80", "low": None, "high": None},
         {"name": "S. Typhi H", "unit": "titer", "ref_male": "<1:80", "ref_female": "<1:80", "low": None, "high": None},
     ]},
    {"code": "TYPH", "name": "Typhidot (IgG & IgM)", "category": "Serology", "specimen": "Serum", "price": 500, "tat_hours": 4,
     "parameters": [
         {"name": "Typhidot IgG", "unit": "", "ref_male": "Negative", "ref_female": "Negative", "low": None, "high": None},
         {"name": "Typhidot IgM", "unit": "", "ref_male": "Negative", "ref_female": "Negative", "low": None, "high": None},
     ]},

    # Virology
    {"code": "HBSAG", "name": "HBsAg (Hepatitis B Surface Antigen)", "category": "Virology", "specimen": "Serum", "price": 450, "tat_hours": 6,
     "parameters": [{"name": "HBsAg", "unit": "", "ref_male": "Non-Reactive", "ref_female": "Non-Reactive", "low": None, "high": None}]},
    {"code": "HCV", "name": "Anti-HCV (Hepatitis C)", "category": "Virology", "specimen": "Serum", "price": 600, "tat_hours": 6,
     "parameters": [{"name": "Anti-HCV", "unit": "", "ref_male": "Non-Reactive", "ref_female": "Non-Reactive", "low": None, "high": None}]},
    {"code": "HIV", "name": "Anti-HIV 1 & 2 (Screening)", "category": "Virology", "specimen": "Serum", "price": 450, "tat_hours": 6,
     "parameters": [{"name": "Anti-HIV", "unit": "", "ref_male": "Non-Reactive", "ref_female": "Non-Reactive", "low": None, "high": None}]},
    {"code": "DEN", "name": "Dengue NS1 + IgG/IgM", "category": "Virology", "specimen": "Serum", "price": 1000, "tat_hours": 6,
     "parameters": [
         {"name": "Dengue NS1 Ag", "unit": "", "ref_male": "Negative", "ref_female": "Negative", "low": None, "high": None},
         {"name": "Dengue IgG", "unit": "", "ref_male": "Negative", "ref_female": "Negative", "low": None, "high": None},
         {"name": "Dengue IgM", "unit": "", "ref_male": "Negative", "ref_female": "Negative", "low": None, "high": None},
     ]},
    {"code": "MP", "name": "Malarial Parasite Smear (MP)", "category": "Microbiology", "specimen": "EDTA Blood", "price": 400, "tat_hours": 4,
     "parameters": [{"name": "MP Smear", "unit": "", "ref_male": "Not Seen", "ref_female": "Not Seen", "low": None, "high": None}]},

    # Urinalysis
    {"code": "URE", "name": "Urine Complete Examination (R/E)", "category": "Urinalysis", "specimen": "Urine", "price": 200, "tat_hours": 2,
     "parameters": [
         {"name": "Color", "unit": "", "ref_male": "Pale Yellow", "ref_female": "Pale Yellow", "low": None, "high": None},
         {"name": "Appearance", "unit": "", "ref_male": "Clear", "ref_female": "Clear", "low": None, "high": None},
         {"name": "pH", "unit": "", "ref_male": "5.0-8.0", "ref_female": "5.0-8.0", "low": 5.0, "high": 8.0},
         {"name": "Specific Gravity", "unit": "", "ref_male": "1.005-1.030", "ref_female": "1.005-1.030", "low": 1.005, "high": 1.030},
         {"name": "Protein", "unit": "", "ref_male": "Negative", "ref_female": "Negative", "low": None, "high": None},
         {"name": "Glucose", "unit": "", "ref_male": "Negative", "ref_female": "Negative", "low": None, "high": None},
         {"name": "Ketones", "unit": "", "ref_male": "Negative", "ref_female": "Negative", "low": None, "high": None},
         {"name": "Pus Cells", "unit": "/HPF", "ref_male": "0-5", "ref_female": "0-5", "low": 0, "high": 5},
         {"name": "RBCs", "unit": "/HPF", "ref_male": "0-2", "ref_female": "0-2", "low": 0, "high": 2},
     ]},
    {"code": "UCS", "name": "Urine Culture & Sensitivity", "category": "Microbiology", "specimen": "Urine", "price": 800, "tat_hours": 72,
     "parameters": [{"name": "Culture", "unit": "", "ref_male": "No Growth", "ref_female": "No Growth", "low": None, "high": None}]},
    {"code": "SRE", "name": "Stool Complete Examination (R/E)", "category": "Pathology", "specimen": "Stool", "price": 300, "tat_hours": 4,
     "parameters": [
         {"name": "Consistency", "unit": "", "ref_male": "Formed", "ref_female": "Formed", "low": None, "high": None},
         {"name": "Occult Blood", "unit": "", "ref_male": "Negative", "ref_female": "Negative", "low": None, "high": None},
         {"name": "Ova / Cysts", "unit": "", "ref_male": "Not Seen", "ref_female": "Not Seen", "low": None, "high": None},
     ]},
    {"code": "PREG", "name": "Pregnancy Test (Urine)", "category": "Endocrinology", "specimen": "Urine", "price": 150, "tat_hours": 1,
     "parameters": [{"name": "hCG", "unit": "", "ref_male": "N/A", "ref_female": "Negative", "low": None, "high": None}]},
]

SEED_PATIENTS = [
    {"mr_number": "LC-2026-0001", "name": "Muhammad Ahmed Khan", "age": 45, "gender": "Male", "phone": "+92-300-1234567", "referring_physician": "Dr. Imran Siddiqui", "address": "Lahore"},
    {"mr_number": "LC-2026-0002", "name": "Ayesha Fatima", "age": 32, "gender": "Female", "phone": "+92-301-2345678", "referring_physician": "Dr. Sarah Tariq", "address": "Karachi"},
    {"mr_number": "LC-2026-0003", "name": "Hamza Ali Raza", "age": 28, "gender": "Male", "phone": "+92-302-3456789", "referring_physician": "Dr. Imran Siddiqui", "address": "Islamabad"},
    {"mr_number": "LC-2026-0004", "name": "Sana Malik", "age": 54, "gender": "Female", "phone": "+92-303-4567890", "referring_physician": "Dr. Faisal Khan", "address": "Burewala"},
    {"mr_number": "LC-2026-0005", "name": "Zain-ul-Abideen", "age": 60, "gender": "Male", "phone": "+92-304-5678901", "referring_physician": "Dr. Sarah Tariq", "address": "Multan"},
    {"mr_number": "LC-2026-0006", "name": "Fatima Noor", "age": 25, "gender": "Female", "phone": "+92-305-6789012", "referring_physician": "Dr. Imran Siddiqui", "address": "Faisalabad"},
    {"mr_number": "LC-2026-0007", "name": "Bilal Hussain", "age": 38, "gender": "Male", "phone": "+92-306-7890123", "referring_physician": "Dr. Faisal Khan", "address": "Lahore"},
    {"mr_number": "LC-2026-0008", "name": "Mariam Iqbal", "age": 42, "gender": "Female", "phone": "+92-307-8901234", "referring_physician": "Dr. Sarah Tariq", "address": "Chichawatni"},
]
